spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot-jpa
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate: # Funcionará como nuestra ORM
      ddl-auto: create-drop
    database: postgresql
    show-sql: true